<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-12-22T15:33:06+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.2',
    'version_db_installed' => '20190925072210',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1577010902,
        'do_page_reindex_check' => false,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
