<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-12-22T11:32:08+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Ugly Blog',
        ],
    ],
];
